name: CI with uv

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install uv
      run: curl -Ls https://astral.sh/uv/install.sh | sh

    - name: Create virtual environment
      run: uv venv

    - name: Activate environment and install dependencies
      run: |
        source .venv/bin/activate
        uv pip install .[dev]

    - name: Run pre-commit checks
      run: pre-commit run --all-files || true

    - name: Check if app.py exists before running Streamlit
      run: |
        if [ -f src/app.py ]; then
          echo "src/app.py found. You can now run Streamlit manually if needed.";
        else
          echo "src/app.py not found. Skipping Streamlit execution.";
        fi